// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bg: typeof import('./components/Bg.vue')['default']
    Cursor: typeof import('./components/Cursor/index.vue')['default']
    GlassCard: typeof import('./components/GlassCard.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Navlink: typeof import('./components/Navlink.vue')['default']
    Switch: typeof import('./components/Switch/index.vue')['default']
  }
}

export { }
